config/routes.rb
Rails.application.routes.draw do
  namespace :user do
    get 'users/index'
    get 'users/show'
    get 'users/edit'
    get 'users/update'
    get 'users/create'
    get 'users/destroy'
  end
get 'users/destroy' => "users#delete"

# 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:passwords], controllers: {
  sessions: "admin/sessions"
}

# ユーザー用
# URL /users/sign_in ...
  devise_for :user, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

  devise_scope :user do
  post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

namespace :admin do
  root to: "homes#top", as: 'top'
   get "homes/about" => "homes#about"
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :vegetainable_reviews, only: [:show, :destroy]
  end
  resources :comments, only: [:destroy]

end

scope module: :user do
  root to: 'homes#top'
  get "homes/about" => "homes#about"
  resources :vegetainable_reviews, only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resource :favorite, only: [:create, :destroy]
  get "search" => "searches#search"
  get 'users/my_page' => "users#mypage", as: 'my_page'
  get '/users/my_page/edit' => "users#edit", as: 'edit_my_page'
  patch '/users/my_page' => "users#update", as: 'update_my_page'
  get '/users/my_page/withdraw_confirmation' => "users#withdraw_confirmation", as: 'withdraw_confirmation_my_page'
  patch '/users/my_page/withdraw' => "users#withdraw", as: 'withdraw_my_page'

  resources :users, only: [:index, :show]

  # get 'vegetainable_review/:id/favorite/new' => "favorites#new", as: 'new_favorite'
  # post 'vegetainable_review/:id/favorite/new' => "favorites#new", as: 'favorite'
  # get '/vegetainable_review/:id/favorite/:id/edit' => "favorite#edit", as: 'edit_favorite'
  # patch '/vegetainable_review/:id/favorite/:id' => "favorite#update", as: 'update_favorite'
  # delete '/vegetainable_review/:id/favorite/:id' => "favorite#destroy", as: 'destroy_favorite'

end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vegetainable_review.rb
class VegetainableReview < ApplicationRecord

  has_one_attached :image

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :vegetainable_reviews_tags, dependent: :destroy
  has_many :tags, through: :vegetainable_reviews_tags

  validates :title, presence: true
  validates :name, presence: true
  validates :price, presence: true
  validates :amount, presence: true
  validates :caption, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def get_image(width, height)
    if image.attached?
      image.variant(resize_to_limit: [width, height])
    else
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @vegetainable_review = VegetainableReview.where("shop_name LIKE?","#{word}")
      @vegetainable_review += VegetainableReview.where("farmer_name LIKE?","#{word}")
      @vegetainable_review += VegetainableReview.where("area LIKE?","#{word}")
      @vegetainable_review += VegetainableReview.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @vegetainable_review = VegetainableReview.where("shop_name LIKE?","#{word}%")
      @vegetainable_review += VegetainableReview.where("farmer_name LIKE?","#{word}")
      @vegetainable_review += VegetainableReview.where("area LIKE?","#{word}")
      @vegetainable_review += VegetainableReview.where("name LIKE?","#{word}")
    elsif search == "backward_match"
      @vegetainable_review = VegetainableReview.where("shop_name LIKE?","%#{word}")
      @vegetainable_review += VegetainableReview.where("farmer_name LIKE?","#{word}")
      @vegetainable_review += VegetainableReview.where("area LIKE?","#{word}")
      @vegetainable_review += VegetainableReview.where("name LIKE?","#{word}")
    elsif search == "partial_match"
      @vegetainable_review = VegetainableReview.where("shop_name LIKE?","%#{word}%")
      @vegetainable_review += VegetainableReview.where("farmer_name LIKE?","#{word}")
      @vegetainable_review += VegetainableReview.where("area LIKE?","#{word}")
      @vegetainable_review += VegetainableReview.where("name LIKE?","#{word}")
    else
      @vegetainable_review = VegetainableReview.all
    end
  end

  # def self.looks(search, word)
  #   if search == 'word'
  #     where("shop_name LIKE ?", "%#{word}%")
  #   elsif search == 'word'
  #     where("farmer_name LIKE ?", "%#{word}%")
  #   else
  #     all
  #   end
  # end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @vegetainable_reviews = VegetainableReview.all
    @users = User.all
    @user = @users.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @vegetainable_reviews = @user.vegetainable_reviews
    @vegetainable_review = @vegetainable_reviews.page(params[:page])
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to edit_admin_user_path(@user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.is_active = false if not params[:user][:is_active]
    user.update(user_params)
    redirect_to admin_users_path(user.id)
  end

  private

  def user_params
    params.require(:user).permit(:admin_id, :email, :user_id, :nickname, :name, :encrypted_password, :image, :telephone_number, :is_active, tag_ids: [])
  end


end

app/controllers/admin/vegetainable_reviews_controller.rb
class Admin::VegetainableReviewsController < ApplicationController

  def index
    @vegetainable_reviews = VegetainableReview.all
  end

  def show
    # @user = User.find(params[:user_id])
    @vegetainable_review = VegetainableReview.find(params[:id])
    @user = @vegetainable_review.user
    if @vegetainable_review.nil?
      redirect_to admin_users_path
    end
    # @user_id = @user.vegetainable_reviews
    # redirect_to admin_user_vegetainable_review_path(@user)
  end

  def destroy
    @vegetainable_review = VegetainableReview.find(params[:id])
    @vegetainable_review.destroy
    user = User.find(params[:user_id])
    redirect_to admin_user_path(user.id), notice: '★ レビューが１件削除されました！'
  end


end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController

  def create
    vegetainable_review = VegetainableReview.find(params[:vegetainable_review_id])
    comment = current_user.comments.new(comment_params)
    comment.vegetainable_review_id = vegetainable_review.id
    comment.save
    redirect_to vegetainable_review_path(vegetainable_review)
  end

  def destroy
    comment = current_user.comments
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_back fallback_location: root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController

  def create
    vegetainable_review = VegetainableReview.find(params[:format])
    favorite = current_user.favorites.new(vegetainable_review_id: vegetainable_review.id)
    favorite.save
    redirect_to vegetainable_review_path(vegetainable_review)
  end

  def destroy
    vegetainable_review = VegetainableReview.find(params[:format])
    favorite = current_user.favorites.find_by(vegetainable_review_id: vegetainable_review.id)
    favorite.destroy
    redirect_to vegetainable_review_path(vegetainable_review)
  end


end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController

  before_action :authenticate_user!

  def show
    @vegetainable_review = VegetainableReview.find(params[:id])
  end


end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password, :telephone_number, :nickname, :profile_image])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end


end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @vegetainable_reviews = VegetainableReview.looks(params[:search], params[:word])
    end
  end

end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController

  before_action :user_state, only: [:create]

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: '★ゲストユーザーとしてログインしました！'
  end

#   def destroy
#   byebug
#   session[:user_id] = nil
#   redirect_to root_path, notice: 'ログアウトしました'
# 　end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def user_state
    @user = User.find_by(email: params[:user][:email])
    return if !@user
    if @user.valid_password?(params[:user][:password]) && !@user.is_active
      redirect_to new_user_registration_path
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :email, :encrypted_password])
  end

  private

def user_state
    @user = User.find_by(email: params[:user][:email])
    return if !@user
    if @user.valid_password?(params[:user][:password]) && !@user.is_active
      redirect_to new_user_registration_path
    end
end


end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController

  def index
    @vegetainable_review = VegetainableReview.find(params[:id])
    @vegetainable_reviews = @user.vegetainable_review
  end

  def show
    @user = User.find(params[:id])
    @vegetainable_reviews = @user.vegetainable_reviews
    # @vegetainable_reviews = params[:tag_id].present? ? Tag.find(params[:tag_id]).user.vegetainable_reviews : VegetainableReview.find(params.id)
    @vegetainable_reviews = @vegetainable_reviews.page(params[:page])
    # @comment = Comment.new
    # @comments = Comments.find(params[:id])
    # @comment = @vegetainable_reviews.comment
  end

  def mypage
    @user = current_user
    @vegetainable_reviews = @user.vegetainable_reviews
    @vegetainable_reviews = @vegetainable_reviews.page(params[:page])
  end

  def edit
    @user = current_user
  end

  def update
    user = current_user
    user.update(user_params)
    redirect_to my_page_path(user_params)
  end

  def withdraw_confirmation
  end

  def withdraw
    user = current_user
    user.update(is_active: false)
    reset_session
    redirect_to new_user_session_path
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  private

  def user_params
    params.require(:user).permit(:admin_id, :email, :user_id, :nickname, :name, :encrypted_password, :profile_image, :telephone_number, :is_active, tag_ids: [])
  end

  def vegetainable_review_params
    params.require(:vegetainable_review).permit(:title, :name, :price, :amount, :farmer_name, :user_id, :shop_name, :image, :caption, :area, tag_ids: [])
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin/vegetainable_reviews_helper.rb
module Admin::VegetainableReviewsHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/views/user/vegetainable_reviews/_search.html.erb
<div class="container">
  <div class="row">
    <% if user_signed_in? %>
  <div class="search_form mb-3">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <tr>
        <td><%= f.text_field :word, class: "mb-2"%></td>
        <td><%= f.select :range, options_for_select([["農家 or 購入先 or 産地 or 野菜","vegetainable_review"],["アカウント名 or ニックネーム or 会員ID","User"]]) %></td>
        <td><%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %></td>
        <td><%= f.submit "検索", class: "btn btn-warning ml-2 mt-2 " %></td>
      </tr>
    <% end %>
  </div>
<% end %>
  </div>
</div>

app/views/user/vegetainable_reviews/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 pt-5">
      <div>
        <p class="mb-5 h5"><%= flash[:notice] %></p>
      </div>

    <div class="col-md-2 mt-2">
      <%= form_tag vegetainable_reviews_path, method: :get, class: 'boards__searchForm' do %>
      <table>
        <%= select_tag :tag_id,
                       options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                       {
                         prompt: '＃ハッシュタグ投稿を見る',
                         onchange: 'submit(this.form);'
                       }
        %>
        </table>
      <% end %>
    </div>
    <div class="col-md-3 mt-4">
    <%= render 'user/vegetainable_reviews/search' %>
    </div>
  </div>
</div>

    <% @vegetainable_reviews.each do |vegetainable_review| %>
    <table>
      <div class="row">
        <div class="col-3 mt-5 pt-4 mb-3">
            <tr>
              <td>
                <%#= link_to vegetainable_review_path(vegetainable_review.id) do %>
                <% if current_user %>
                  <%= link_to vegetainable_review_path(vegetainable_review.id) do %>
                  <%= image_tag vegetainable_review.get_image(300, 200) if vegetainable_review.image.attached? %>
                  <% end %>
                <% else %>
                   <%= link_to admin_user_vegetainable_review_path(current_admin.id ,vegetainable_review.id) do %>
                     <%= image_tag vegetainable_review.get_image(300, 200) if vegetainable_review.image.attached? %>
                   <% end %>
                <% end %>
              </td>
            </tr>
        </div>
        <div class="col-4">
            <tr>
              <th class="p-3">
              <%= link_to user_path(vegetainable_review.user) do %>
              <%= image_tag vegetainable_review.user.get_profile_image(80, 80) %>
              @<%= vegetainable_review.user.name %> ( <%= vegetainable_review.user.nickname %> )</th>
              <% end %>
            </tr>
            <tr>
              <th class="p-3"><%= vegetainable_review.title %></th>
            </tr>
            <tr>
              <td class="pt-1 pb-3 pl-3"><%= vegetainable_review.caption %></td>
            </tr>
            <tr>
              <td class="p-3">農家：<%= vegetainable_review.farmer_name %></td>
            </tr>
            <% if current_user %>
              <tr>
                <td>
                  <% if current_user.email != 'guest@vegetainable.com'%>
                  <%= link_to "もう一度レビューを投稿する", new_vegetainable_review_path, class: "btn btn-warning ml-4 mt-3"%>
                  <% end %>
                  </td>
              </tr>
            <% end %>
            <hr class="p-2">
        </div>
      </div>
    </table>
    <% end %>
    <div class="pl-3 m-4 pt-4 h5">
    <tr>
      <td><%= paginate @vegetainable_reviews %></td>
    </tr>
    </div>
</div>

app/views/user/vegetainable_reviews/show.html.erb
<div class="container">
  <div calss="row">
    <div class="col-md-12">
        <p class="mb-6"><%= flash[:notice] %></p>
    </div>
  </div>

  <%= form_with model: @vegetainable_review, method: :patch, url: vegetainable_review_path do |f| %>
  <div class="row">
    <div class="col-md-5">
      <table>
      <tr>
         <th class="pt-3 h5">
           <%= image_tag @vegetainable_review.user.get_profile_image(80, 80) %>
           @<%= @vegetainable_review.user.name %> ( <%= @vegetainable_review.user.nickname %> )</th>
      </tr>
      <tr>
        <td class="pt-4">
            <!--画像-->
            <% if @vegetainable_review.image.attached? %>
            <%= image_tag @vegetainable_review.image, size: "310x250" %>
            <% else %>
            <%= image_tag 'no_image', size: "170x200" %>
            <% end %>
          <!--いいね機能-->
          <% if @vegetainable_review.favorited_by?(current_user) %>
            <p class="text-right">
              <%= link_to favorite_path(@vegetainable_review), method: :delete do %>
              ♥ <%= @vegetainable_review.favorites.count %> いいね
            <% end %>
            </p>
            <% else %>
            <p class="text-right">
              <%= link_to favorite_path(@vegetainable_review), method: :post do %>
              ♡ <%= @vegetainable_review.favorites.count %> いいね
            <% end %>
            </p>
          <% end %>
        </td>
      </tr>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-7">
      <table>
        <tr>
            <td class="pt-2 pb-2"><h4><%= @vegetainable_review.title %></h4></td>
        </tr>
        <tr>
            <th></th>
        </tr>
        <tr>
            <td class="p-3"><%= @vegetainable_review.caption %></td>
        </tr>
        <tr>
          <td class="p-4">
          <% @vegetainable_review.tags.each do |tag| %>
          # <%= link_to tag.name,vegetainable_reviews_path(tag_id: tag.id) %>
          <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <table class="m-1 mt-4">
        <tr>
           <th class="border border-3 p-3">購入した野菜</th>
           <th class="border border-3 p-3">産地</th>
           <th class="border border-3 p-3">購入価格</th>
           <th class="border border-3 p-3">個数</th>
           <th class="border border-3 p-3">農家</th>
           <th class="border border-3 p-3 w-40">購入先</th>
        </tr>
        <tr>
          <td class="border border-3 p-3"><%= @vegetainable_review.name %></td>
          <td class="border border-3 p-3"><%= @vegetainable_review.area %></td>
          <td class="border border-3 p-3"><%= @vegetainable_review.price %>円</td>
          <td class="border border-3 p-3"><%= @vegetainable_review.amount %>個</td>
          <td class="border border-3 p-3"><%= @vegetainable_review.farmer_name %></td>
          <td class="border border-3 p-3"><%= @vegetainable_review.shop_name %></td>
        </tr>
        </table>
      </div>
    </div>

  <% if current_user.email != 'guest@vegetainable.com'%>
  <div class="row">
    <div class="col-md-12 mt-3">
      <tr>
        <td><%= link_to "レビューを編集する", edit_vegetainable_review_path, class: "btn btn-success pt-2 mt-4"%></td>
      </tr>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 mt-3">
      <tr>
        <td><%= link_to "もう一度レビューを投稿する", new_vegetainable_review_path, class: "btn btn-warning p-2 mt-4"%></td>
      </tr>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-12 mt-3 mb-5">
      <tr>
         <td><%= link_to "<< レビューの一覧へ戻る", vegetainable_reviews_path, class: "btn btn-warning p-2 mt-4"%></td>
          <% if @vegetainable_review.user == current_user %>
            <%= link_to "削除", vegetainable_review_path(@vegetainable_review), method: :delete, class: "btn btn-outline-warning p-2 ml-4 mt-4", data: { confirm: '本当に削除しますか？' }  %>
          <% end %>
         </td>
      </tr>
    </div>
  </div>
  <% end %>

    <div class="row">
      <div class="col-md-12">
        <p class="border-top p-3">コメント件数：<%= @vegetainable_review.comments.count %></p>
        <% @vegetainable_review.comments.each do |comment| %>
        </div>
        <div class="col-md-5">
          <tr>
            <td><%= image_tag comment.user.get_profile_image(60,60) %> @<%= comment.user.name %>さん</td>
          </tr>
        </div>
        <div class="col-md-12">
          <tr>
            <td><%= comment.created_at.strftime('%Y/%m/%d') %>：</td>
            <td><%= comment.content %></td>
            <td>
              <% if user_signed_in? && current_user.id %>
                <%= button_to "削除する", vegetainable_review_comment_path(@vegetainable_review.id,comment.id), method: :delete, class: "mt-2 mb-4 btn btn-secondary" %>
              <% end %>
            </td>
          </tr>
        </div>
        <% end %>
        <div class="col-md-12">
        <%= form_with url: vegetainable_review_comments_path(@vegetainable_review.id), model: @comment do |f| %>
          <%= f.text_area :content, rows: '5', placeholder: "コメントはこちらへ", class: "mt-4 px-5" %>
          <%= f.submit "送信する", class: "btn btn-warning p-2 mt-4 mb-5" %>
        <% end %>
      </div>
    </div>
</div>