config/routes.rb
Rails.application.routes.draw do
  namespace :user do
    get 'users/index'
    get 'users/show'
    get 'users/edit'
    get 'users/update'
    get 'users/create'
    get 'users/destroy'
  end
get 'users/destroy' => "users#delete"

# 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:passwords], controllers: {
  sessions: "admin/sessions"
}

# ユーザー用
# URL /users/sign_in ...
  devise_for :user, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

  devise_scope :user do
  post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

namespace :admin do
  root to: "homes#top", as: 'top'
   get "homes/about" => "homes#about"
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :vegetainable_reviews, only: [:show, :destroy]
  end
  resources :comments, only: [:destroy]

end

scope module: :user do
  root to: 'homes#top'
  get "homes/about" => "homes#about"
  resources :vegetainable_reviews, only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resource :favorite, only: [:create, :destroy]
  get "search" => "searches#search"
  get 'users/my_page' => "users#mypage", as: 'my_page'
  get '/users/my_page/edit' => "users#edit", as: 'edit_my_page'
  patch '/users/my_page' => "users#update", as: 'update_my_page'
  get '/users/my_page/withdraw_confirmation' => "users#withdraw_confirmation", as: 'withdraw_confirmation_my_page'
  patch '/users/my_page/withdraw' => "users#withdraw", as: 'withdraw_my_page'

  resources :users, only: [:index, :show]

  # get 'vegetainable_review/:id/favorite/new' => "favorites#new", as: 'new_favorite'
  # post 'vegetainable_review/:id/favorite/new' => "favorites#new", as: 'favorite'
  # get '/vegetainable_review/:id/favorite/:id/edit' => "favorite#edit", as: 'edit_favorite'
  # patch '/vegetainable_review/:id/favorite/:id' => "favorite#update", as: 'update_favorite'
  # delete '/vegetainable_review/:id/favorite/:id' => "favorite#destroy", as: 'destroy_favorite'

end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :vegetainable_reviews, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   belongs_to :admin, optional: true

   has_one_attached :profile_image

  def get_profile_image(width, height)
  if profile_image.blank?
    file_path = Rails.root.join('app/assets/images/716.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(email: 'guest@vegetainable.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.telephone_number = "09000000000"
      user.name = "ゲストユーザー"
      user.nickname = "ゲストユーザー"
    end
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?","#{word}")
      @user += User.where("nickname LIKE?","#{word}")
      @user += User.where("id LIKE?","#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}")
      @user += User.where("nickname LIKE?","#{word}")
      @user += User.where("id LIKE?","#{word}")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","#{word}")
      @user += User.where("nickname LIKE?","#{word}")
      @user += User.where("id LIKE?","#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","#{word}")
      @user += User.where("nickname LIKE?","#{word}")
      @user += User.where("id LIKE?","#{word}")
    else
      @vegetainable_review = VegetainableReview.all
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @vegetainable_reviews = VegetainableReview.all
    @users = User.all
    @user = @users.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @vegetainable_reviews = @user.vegetainable_reviews
    @vegetainable_review = @vegetainable_reviews.page(params[:page])
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to edit_admin_user_path(@user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.is_active = false if not params[:user][:is_active]
    user.update(user_params)
    redirect_to admin_users_path(user.id)
  end

  private

  def user_params
    params.require(:user).permit(:admin_id, :email, :user_id, :nickname, :name, :encrypted_password, :image, :telephone_number, :is_active, tag_ids: [])
  end


end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController

  def create
    vegetainable_review = VegetainableReview.find(params[:vegetainable_review_id])
    comment = current_user.comments.new(comment_params)
    comment.vegetainable_review_id = vegetainable_review.id
    comment.save
    redirect_to vegetainable_review_path(vegetainable_review)
  end

  def destroy
    comment = current_user.comments
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_back fallback_location: root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController

  def create
    vegetainable_review = VegetainableReview.find(params[:format])
    favorite = current_user.favorites.new(vegetainable_review_id: vegetainable_review.id)
    favorite.save
    redirect_to vegetainable_review_path(vegetainable_review)
  end

  def destroy
    vegetainable_review = VegetainableReview.find(params[:format])
    favorite = current_user.favorites.find_by(vegetainable_review_id: vegetainable_review.id)
    favorite.destroy
    redirect_to vegetainable_review_path(vegetainable_review)
  end


end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController

  before_action :authenticate_user!

  def show
    @vegetainable_review = VegetainableReview.find(params[:id])
  end


end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password, :telephone_number, :nickname, :profile_image])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end


end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @vegetainable_reviews = VegetainableReview.looks(params[:search], params[:word])
    end
  end

end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController

  before_action :user_state, only: [:create]

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: '★ゲストユーザーとしてログインしました！'
  end

#   def destroy
#   byebug
#   session[:user_id] = nil
#   redirect_to root_path, notice: 'ログアウトしました'
# 　end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def user_state
    @user = User.find_by(email: params[:user][:email])
    return if !@user
    if @user.valid_password?(params[:user][:password]) && !@user.is_active
      redirect_to new_user_registration_path
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :email, :encrypted_password])
  end

  private

def user_state
    @user = User.find_by(email: params[:user][:email])
    return if !@user
    if @user.valid_password?(params[:user][:password]) && !@user.is_active
      redirect_to new_user_registration_path
    end
end


end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController

  def index
    @vegetainable_review = VegetainableReview.find(params[:id])
    @vegetainable_reviews = @user.vegetainable_review
  end

  def show
    @user = User.find(params[:id])
    @vegetainable_reviews = @user.vegetainable_reviews
    # @vegetainable_reviews = params[:tag_id].present? ? Tag.find(params[:tag_id]).user.vegetainable_reviews : VegetainableReview.find(params.id)
    @vegetainable_reviews = @vegetainable_reviews.page(params[:page])
    # @comment = Comment.new
    # @comments = Comments.find(params[:id])
    # @comment = @vegetainable_reviews.comment
  end

  def mypage
    @user = current_user
    @vegetainable_reviews = @user.vegetainable_reviews
    @vegetainable_reviews = @vegetainable_reviews.page(params[:page])
  end

  def edit
    @user = current_user
  end

  def update
    user = current_user
    user.update(user_params)
    redirect_to my_page_path(user_params)
  end

  def withdraw_confirmation
  end

  def withdraw
    user = current_user
    user.update(is_active: false)
    reset_session
    redirect_to new_user_session_path
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  private

  def user_params
    params.require(:user).permit(:admin_id, :email, :user_id, :nickname, :name, :encrypted_password, :profile_image, :telephone_number, :is_active, tag_ids: [])
  end

  def vegetainable_review_params
    params.require(:vegetainable_review).permit(:title, :name, :price, :amount, :farmer_name, :user_id, :shop_name, :image, :caption, :area, tag_ids: [])
  end

end

app/controllers/user/vegetainable_reviews_controller.rb
class User::VegetainableReviewsController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    # @vegetainable_reviews = VegetainableReview.all
    @vegetainable_reviews = params[:tag_id].present? ? Tag.find(params[:tag_id]).vegetainable_reviews : VegetainableReview.all
    @vegetainable_reviews = @vegetainable_reviews.page(params[:page])
  end

  def show
    @vegetainable_review = VegetainableReview.find(params[:id])
    @comment = Comment.new
  end

  def new
    @vegetainable_review = VegetainableReview.new
  end

  def create
    @vegetainable_review = VegetainableReview.new(vegetainable_review_params)
    @vegetainable_review.user_id = current_user.id
    if @vegetainable_review.save
      flash[:notice] = "★ レビューが投稿されました！"
      redirect_to vegetainable_review_path(@vegetainable_review.id)
    else
      render :new
    end

  end

  def edit
    @vegetainable_review = VegetainableReview.find(params[:id])
  end

  def update
    vegetainable_review = VegetainableReview.find(params[:id])
    vegetainable_review.update(vegetainable_review_params)
    redirect_to vegetainable_review_path(vegetainable_review.id)
  end

  def destroy
    @vegetainable_review = VegetainableReview.find(params[:id])
    @vegetainable_review.destroy
    redirect_to vegetainable_reviews_path, notice: '★ １件削除されました！'
  end

  private

  def is_matching_login_user
    vegetainable_review = VegetainableReview.find(params[:id])
    unless vegetainable_review.user.id == current_user.id
      redirect_to vegetainable_review_path(vegetainable_review.id)
    end
  end

  def vegetainable_review_params
    params.require(:vegetainable_review).permit(:title, :name, :price, :amount, :farmer_name, :user_id, :shop_name, :image, :caption, :area, tag_ids: [])
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/helpers/user/vegetainable_reviews_helper.rb
module User::VegetainableReviewsHelper
end

app/views/user/users/_mypage_show.html.erb
<!-- user/usersのmypage.html.erbとshow.html.erbの部分テンプレート  -->
<!-- 「該当のユーザー投稿一覧画面」の更新や修正はここで行う　-->
<div class="container">
       <div class="row">
            <div class="mt-5 p-1 col-sm-12">
            <h5>@<%= @user.name %> ( <%= @user.nickname %> ) さんのレビュー投稿一覧</h5>
            </div>
        </div>
  <div class="row">
    <div class="col-sm-5 pt-5 ml-5 mb-5">
    <table>
      <%= form_tag vegetainable_reviews_path, method: :get, class: 'boards__searchForm' do %>
      <%= select_tag :tag_id,
                     options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                     {
                       prompt: 'ハッシュタグ検索',
                       onchange: 'submit(this.form);'
                     }
      %>
    <% end %>
    </table>
    </div>
  </div>

  <table>
    <tbody class="col-sm-12 mt-5">

      <% @vegetainable_reviews.each do |vegetainable_review| %>
         <tr>
              <td>
                <%= link_to vegetainable_review_path(vegetainable_review.id) do %>
                  <%= image_tag vegetainable_review.get_image(300, 200) if vegetainable_review.image.attached? %>
                <% end %>
              </td>
            </tr>
            <tr>
              <th class="p-3">
              <%= image_tag vegetainable_review.user.get_profile_image(80, 80) %>
              @<%= vegetainable_review.user.name %> ( <%= vegetainable_review.user.nickname %> )</th>
            </tr>
        <tr>
          <th class="p-3"><%= vegetainable_review.title %></th>
        </tr>
        <tr>
          <td class="pt-1 pb-3 pl-3"><%= vegetainable_review.caption %></td>
        </tr>
        <tr>
          <td class="p-3">農家：<%= vegetainable_review.farmer_name %><hr clas="pt-3"></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="pl-3 m-4 pt-4 h5 col-sm-4">
    <tr>
      <td><%= paginate @vegetainable_reviews %></td>
    </tr>
  </div>
    <div class="col-sm-10 my-3 pt-3">
      <tr>
      <%= link_to "<< 全レビュー投稿一覧へ戻る", vegetainable_reviews_path, class: "btn btn-warning p-2 mr-4 mb-5" %>
    </tr>
    </div>
</div>

app/views/user/users/edit.html.erb
<div class="container">
  <div class="row">
    <table>
    <div class="mt-5 p-1 col-md-4 text-center">
    <h5>@<%= @user.name %> ( <%= @user.nickname %> ) さんの会員情報編集</h5>
    </div>
    </table>
  </div>

  <div class="row">
    <div class="col-md-12 mt-5">
        <%= form_with model: @user, method: :patch, url: update_my_page_path(@user) do |f| %>
        <table>
            <tr>
              <td class="w-40">プロフィール画像</td>
              <td class="pl-2"><%= f.file_field :profile_image, accept: "image/*", autofocus: true, id:"@user", placeholder:"プロフィール画像" %></td>
            </tr>
            <tr>
              <td class="w-40"><label for="inputName">アカウント名</label></dr>
              <td class="pl-2"><%= f.text_field :name, autofocus: true, id:"@user", placeholder:"アカウント名" %></td>
            </tr>

            <tr>
              <td class="w-40"><label for="inputName">ニックネーム</label></td>
              <td class="pl-2"><%= f.text_field :nickname, autofocus: true, id:"@user", placeholder:"ニックネーム" %></td>
            </tr>

            <tr>
              <td class="w-40"><label for="inputName">電話番号</label></td>
              <td class="pl-2"><%= f.text_field :telephone_number, autofocus: true, id:"@user", placeholder:"電話番号" %></td>
            </tr>

            <tr>
              <td class="w-40"><label for="inputName">メールアドレス</label></td>
              <td class="pl-2"><%= f.text_field :email, autofocus: true, id:"@user", placeholder:"メールアドレス" %></td>
            </tr>
        </table>
          <tr>
            <%= f.submit "変更を保存する", class: "btn btn btn-success p-2 mt-5 mb-4 ml-3" %>
            <% end %>
          </tr>
        <div class="col-md-12 mt-2">
          <tr>
            <%= link_to "<< マイページへ戻る", my_page_path(@user), class: "btn btn-warning p-2 mb-5" %>
          </tr>
          <tr>
            <%= link_to "<< レビュー投稿一覧を見る", vegetainable_reviews_path, class: "btn btn-warning p-2 mb-5" %>
          </tr>
        </div>
      </div>
    </div>
</div>

app/views/user/users/index.html.erb
<div class="container">
    <div class="row">
       <table>
            <div class="mt-5 p-1 col-4">
            <h5>@<%= @user.name %> ( <%= @user.nickname %> ) さんのレビュー投稿一覧</h5>
            </div>
       </table>
    </div>

    <div class="col-5">
      <% @vegetainable_reviews.each do |vegetainable_review| %>
        <tr>
          <th class="p-3"><%= vegetainable_review.title %></th>
        </tr>
        <tr>
          <td class="pt-1 pb-3 pl-3"><%= vegetainable_review.caption %></td>
        </tr>
        <tr>
          <td class="p-3">農家：<%= vegetainable_review.farmer_name %></td>
        </tr>
      <% end %>
    </div>

</div>

app/views/user/users/mypage.html.erb
<div class="container">
    <div class="row">
       <table>
            <div class="mt-5 p-1 col-sm-8">
            <h5>@<%= @user.name %> ( <%= @user.nickname %> ) さんのマイページ</h5>
            </div>
       </table>
    </div>

  <div class="row">
    <div class="col-sm-8">
       <% if @user.email != 'guest@vegetainable.com'%>
        <table class="mt-5 col-md-6 text-center border">
            <tr>
              <th class="py-2 border">プロフィール画像</th>
              <td class="border"><%= image_tag @user.get_profile_image(80, 80) %></td>
            </tr>
            <tr>
                <th class="py-2 border">会員ID</th>
                <td class="border"><%= @user.id %></td>
            </tr>
            <tr>
                <th class="p-2 border">アカウント名</th>
                <td class="border">@<%= @user.name %></td>
            </tr>
            <tr>
                <th class="p-2 border">ニックネーム</th>
                <td class="border"><%= @user.nickname %></td>
            </tr>
             <tr>
                <th class="p-2 border">電話番号</th>
                <td class="border"><%= @user.telephone_number %></td>
            </tr>
             <tr>
                <th class="p-2 border">メールアドレス</th>
                <td class="border"><%= @user.email %></td>
            </tr>
            <tr>
                <th class="p-2 border">会員ステータス</th>
                <td class="border"><%= @user.is_active %></td>
            </tr>
            <tr>
                <th class="p-2 border">会員登録日</th>
                <td class="border"><%= @user.created_at.strftime('%Y/%m/%d') %></td>
            </tr>
        </table>
      <% end %>

         <div class="mt-3 p-5 col-sm-11">
          <tr>
            <% if @user.email != 'guest@vegetainable.com'%>
            <%= link_to "編集する", edit_my_page_path(@user), class: "btn btn-success p-2 mr-4 mb-5" %>
            <% end %>
          </tr>
          <tr>
            <%= link_to "退会する", withdraw_confirmation_my_page_path, class: "btn btn-secondary p-2 mr-4 mb-5" %>
          </tr>
          <tr>
            <%= link_to "<< レビュー投稿一覧へ戻る", vegetainable_reviews_path, class: "btn btn-warning p-2 mr-4 mb-5" %>
          </tr>
         </div>
    </div>

    <!-- 該当ユーザーの投稿一覧 -->
    <!-- user/usersのshow.html.erbと部分テンプレートで表示 -->
    <!-- 更新や修正はuser/usersの_mypage_show.html.erbで編集する  -->
    <div class="m-3">
        <%= render 'user/users/mypage_show.html.erb' %>
      </div>
  </div>
 </div>

app/views/user/users/show.html.erb
<!-- 該当ユーザーの投稿一覧 -->
<!-- user/usersのmypage.html.erbと部分テンプレートで表示 -->
<!-- 更新や修正はuser/usersの_mypage_show.html.erbで編集する  -->
<div class="m-3">
  <%= render 'user/users/mypage_show.html.erb' %>
</div>

app/views/user/users/withdraw_confirmation.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
    <%= form_with model: @user, url: withdraw_my_page_path do |f| %>
    <div class="center-block text-center mt-5">
      <h5 class="font-weight-bold">本当に退会しますか？</h5><br>
      <p>退会すると、会員登録情報や</p>
      <p>これまでの投稿レビューが閲覧できなくなります。</p>
      <p>退会する場合は、「退会する」をクリックしてください。</p>

      <tr>
        <td><%= link_to "退会しない", my_page_path, class: "btn btn-warning mt-5 mr-4 mb-5" %></td>
        <td><%= link_to "退会する", withdraw_my_page_path, method: :patch, class: "btn btn-danger mt-5 mb-5", "data-confirm" => "本当に退会しますか？" %></td>
      </tr>
    <% end %>
    </div>
   </div>
  </div>
</div>