config/routes.rb
Rails.application.routes.draw do
  namespace :user do
    get 'users/index'
    get 'users/show'
    get 'users/edit'
    get 'users/update'
    get 'users/create'
    get 'users/destroy'
  end
get 'users/destroy' => "users#delete"

# 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:passwords], controllers: {
  sessions: "admin/sessions"
}

# ユーザー用
# URL /users/sign_in ...
  devise_for :user, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

  devise_scope :user do
  post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

namespace :admin do
  root to: "homes#top", as: 'top'
   get "homes/about" => "homes#about"
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :vegetainable_reviews, only: [:show, :destroy]
  end
  resources :comments, only: [:destroy]

end

scope module: :user do
  root to: 'homes#top'
  get "homes/about" => "homes#about"
  resources :vegetainable_reviews, only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resource :favorite, only: [:create, :destroy]
  get "search" => "searches#search"
  get 'users/my_page' => "users#mypage", as: 'my_page'
  get '/users/my_page/edit' => "users#edit", as: 'edit_my_page'
  patch '/users/my_page' => "users#update", as: 'update_my_page'
  get '/users/my_page/withdraw_confirmation' => "users#withdraw_confirmation", as: 'withdraw_confirmation_my_page'
  patch '/users/my_page/withdraw' => "users#withdraw", as: 'withdraw_my_page'

  resources :users, only: [:index, :show]

  # get 'vegetainable_review/:id/favorite/new' => "favorites#new", as: 'new_favorite'
  # post 'vegetainable_review/:id/favorite/new' => "favorites#new", as: 'favorite'
  # get '/vegetainable_review/:id/favorite/:id/edit' => "favorite#edit", as: 'edit_favorite'
  # patch '/vegetainable_review/:id/favorite/:id' => "favorite#update", as: 'update_favorite'
  # delete '/vegetainable_review/:id/favorite/:id' => "favorite#destroy", as: 'destroy_favorite'

end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :vegetainable_reviews, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   belongs_to :admin, optional: true

   has_one_attached :profile_image

  def get_profile_image(width, height)
  if profile_image.blank?
    file_path = Rails.root.join('app/assets/images/716.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(email: 'guest@vegetainable.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.telephone_number = "09000000000"
      user.name = "ゲストユーザー"
      user.nickname = "ゲストユーザー"
    end
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?","#{word}")
      @user += User.where("nickname LIKE?","#{word}")
      @user += User.where("id LIKE?","#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}")
      @user += User.where("nickname LIKE?","#{word}")
      @user += User.where("id LIKE?","#{word}")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","#{word}")
      @user += User.where("nickname LIKE?","#{word}")
      @user += User.where("id LIKE?","#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","#{word}")
      @user += User.where("nickname LIKE?","#{word}")
      @user += User.where("id LIKE?","#{word}")
    else
      @vegetainable_review = VegetainableReview.all
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @vegetainable_reviews = VegetainableReview.all
    @users = User.all
    @user = @users.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @vegetainable_reviews = @user.vegetainable_reviews
    @vegetainable_review = @vegetainable_reviews.page(params[:page])
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to edit_admin_user_path(@user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.is_active = false if not params[:user][:is_active]
    user.update(user_params)
    redirect_to admin_users_path(user.id)
  end

  private

  def user_params
    params.require(:user).permit(:admin_id, :email, :user_id, :nickname, :name, :encrypted_password, :image, :telephone_number, :is_active, tag_ids: [])
  end


end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController

  def create
    vegetainable_review = VegetainableReview.find(params[:vegetainable_review_id])
    comment = current_user.comments.new(comment_params)
    comment.vegetainable_review_id = vegetainable_review.id
    comment.save
    redirect_to vegetainable_review_path(vegetainable_review)
  end

  def destroy
    comment = current_user.comments
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_back fallback_location: root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController

  def create
    vegetainable_review = VegetainableReview.find(params[:format])
    favorite = current_user.favorites.new(vegetainable_review_id: vegetainable_review.id)
    favorite.save
    redirect_to vegetainable_review_path(vegetainable_review)
  end

  def destroy
    vegetainable_review = VegetainableReview.find(params[:format])
    favorite = current_user.favorites.find_by(vegetainable_review_id: vegetainable_review.id)
    favorite.destroy
    redirect_to vegetainable_review_path(vegetainable_review)
  end


end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController

  before_action :authenticate_user!

  def show
    @vegetainable_review = VegetainableReview.find(params[:id])
  end


end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password, :telephone_number, :nickname, :profile_image])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end


end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @vegetainable_reviews = VegetainableReview.looks(params[:search], params[:word])
    end
  end

end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController

  before_action :user_state, only: [:create]

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: '★ゲストユーザーとしてログインしました！'
  end

#   def destroy
#   byebug
#   session[:user_id] = nil
#   redirect_to root_path, notice: 'ログアウトしました'
# 　end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def user_state
    @user = User.find_by(email: params[:user][:email])
    return if !@user
    if @user.valid_password?(params[:user][:password]) && !@user.is_active
      redirect_to new_user_registration_path
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :email, :encrypted_password])
  end

  private

def user_state
    @user = User.find_by(email: params[:user][:email])
    return if !@user
    if @user.valid_password?(params[:user][:password]) && !@user.is_active
      redirect_to new_user_registration_path
    end
end


end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController

  def index
    @vegetainable_review = VegetainableReview.find(params[:id])
    @vegetainable_reviews = @user.vegetainable_review
  end

  def show
    @user = User.find(params[:id])
    @vegetainable_reviews = @user.vegetainable_reviews
    # @vegetainable_reviews = params[:tag_id].present? ? Tag.find(params[:tag_id]).user.vegetainable_reviews : VegetainableReview.find(params.id)
    @vegetainable_reviews = @vegetainable_reviews.page(params[:page])
    # @comment = Comment.new
    # @comments = Comments.find(params[:id])
    # @comment = @vegetainable_reviews.comment
  end

  def mypage
    @user = current_user
    @vegetainable_reviews = @user.vegetainable_reviews
    @vegetainable_reviews = @vegetainable_reviews.page(params[:page])
  end

  def edit
    @user = current_user
  end

  def update
    user = current_user
    user.update(user_params)
    redirect_to my_page_path(user_params)
  end

  def withdraw_confirmation
  end

  def withdraw
    user = current_user
    user.update(is_active: false)
    reset_session
    redirect_to new_user_session_path
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  private

  def user_params
    params.require(:user).permit(:admin_id, :email, :user_id, :nickname, :name, :encrypted_password, :profile_image, :telephone_number, :is_active, tag_ids: [])
  end

  def vegetainable_review_params
    params.require(:vegetainable_review).permit(:title, :name, :price, :amount, :farmer_name, :user_id, :shop_name, :image, :caption, :area, tag_ids: [])
  end

end

app/controllers/user/vegetainable_reviews_controller.rb
class User::VegetainableReviewsController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    # @vegetainable_reviews = VegetainableReview.all
    @vegetainable_reviews = params[:tag_id].present? ? Tag.find(params[:tag_id]).vegetainable_reviews : VegetainableReview.all
    @vegetainable_reviews = @vegetainable_reviews.page(params[:page])
  end

  def show
    @vegetainable_review = VegetainableReview.find(params[:id])
    @comment = Comment.new
  end

  def new
    @vegetainable_review = VegetainableReview.new
  end

  def create
    @vegetainable_review = VegetainableReview.new(vegetainable_review_params)
    @vegetainable_review.user_id = current_user.id
    if @vegetainable_review.save
      flash[:notice] = "★ レビューが投稿されました！"
      redirect_to vegetainable_review_path(@vegetainable_review.id)
    else
      render :new
    end

  end

  def edit
    @vegetainable_review = VegetainableReview.find(params[:id])
  end

  def update
    vegetainable_review = VegetainableReview.find(params[:id])
    vegetainable_review.update(vegetainable_review_params)
    redirect_to vegetainable_review_path(vegetainable_review.id)
  end

  def destroy
    @vegetainable_review = VegetainableReview.find(params[:id])
    @vegetainable_review.destroy
    redirect_to vegetainable_reviews_path, notice: '★ １件削除されました！'
  end

  private

  def is_matching_login_user
    vegetainable_review = VegetainableReview.find(params[:id])
    unless vegetainable_review.user.id == current_user.id
      redirect_to vegetainable_review_path(vegetainable_review.id)
    end
  end

  def vegetainable_review_params
    params.require(:vegetainable_review).permit(:title, :name, :price, :amount, :farmer_name, :user_id, :shop_name, :image, :caption, :area, tag_ids: [])
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/helpers/user/vegetainable_reviews_helper.rb
module User::VegetainableReviewsHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mt-5 p-1 col-md-4 text-center">
      <%= form_with model: @user, url: admin_user_path(@user) do |f| %>
      <h5><%= @user.name %><%= @user.nickname %>さんの会員情報編集</h5>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 mt-5">
      <%= form_with model: @user, method: :patch, url: admin_user_path(@user) do |f| %>
      <table>
        <tr>
          <td class="w-40">プロフィール画像</td>
          <td class="pl-2"><%= f.file_field :profile_image, accept: "image/*", autofocus: true, id:"@user", placeholder:"プロフィール画像" %></td>
        </tr>
        <tr>
          <td class="w-40"><label for="inputName">アカウント名</label></dr>
          <td class="pl-2"><%= f.text_field :name, autofocus: true, id:"@user", placeholder:"アカウント名" %></td>
        </tr>

        <tr>
          <td class="w-40"><label for="inputName">ニックネーム</label></td>
          <td class="pl-2"><%= f.text_field :nickname, autofocus: true, id:"@user", placeholder:"ニックネーム" %></td>
        </tr>

        <tr>
          <td class="w-40"><label for="inputName">電話番号</label></td>
          <td class="pl-2"><%= f.text_field :telephone_number, autofocus: true, id:"@user", placeholder:"電話番号" %></td>
        </tr>

        <tr>
          <td class="w-40"><label for="inputName">メールアドレス</label></td>
          <td class="pl-2"><%= f.text_field :email, autofocus: true, id:"@user", placeholder:"メールアドレス" %></td>
        </tr>

        <tr>
          <td class="w-40"><label for="inputName">会員ステータス</label></td>
          <td class="pl-2"><%= f.check_box :is_active, {}, true, false %></td>
        </tr>
      </table>
        <tr>
          <%= f.submit "変更を保存する", class: "btn btn-success p-2 mt-5 mb-4 ml-3" %>
          <% end %>
        </tr>
      <div class="col-12 mt-2">
        <tr>
          <%= link_to "<< 会員詳細へ戻る", admin_user_path(@user), class: "btn btn-warning p-2 mb-5" %>
        </tr>
        <tr>
          <%= link_to "<< レビュー投稿詳細を見る", admin_user_vegetainable_review_path(@user), class: "btn btn-warning p-2 mb-5" %>
        </tr>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
    <div class="row">
       <table>
            <div class="mt-5 p-1 text-center col-md-2 mb-3">
            <h5>会員一覧</h5>
            </div>
       </table>
    </div>
    <div class="row">
        <div class="col-md-12">
        <table class="mt-3 table table-striped">
            <tr>
                <th class="col-md-1">会員ID</th>
                <th class="col-md-2 text-center">アカウント名</th>
                <th class="col-md-2 text-center">ニックネーム</th>
                <th class="col-md-2 text-center">メールアドレス</th>
                <th class="col-md-2 text-center">電話番号</th>
                <th class="col-md-2 text-center">会員登録日</th>
                <th class="col-md-2 text-center">会員ステータス</th>
            </tr>
        </table>
        </div>

        <% @users.each do |user| %>
        <div class="col-md-12">
        <table class="mt-2 mb-2 border-top col-md-12">
            <tr>
                <td class="pt-2 pb-2 col-md-1"><%= user.id %></td>
                <td class="col-md-2 text-center"><%= link_to user.name, admin_user_path(user.id) %></td>
                <td class="col-md-2 text-center"><%= user.nickname %></td>
                <td class="col-md-2 text-center"><%= user.email %></td>
                <td class="col-md-2 text-center"><%= user.telephone_number %></td>
                <td class="col-md-2 text-center"><%= user.created_at.strftime('%Y/%m/%d') %></td>
                <td class="col-md-2 text-center"><%= user.is_active %></td>
            </tr>
        </table>
        </div>
        <% end %>
    </div>
    <footer class="pl-5 border-top pt-3 w-50 col-12 pb-5 text-center">
    <%= paginate @user %>
    </footer>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div calss="row">
    <div class="col-sm-12">
        <p class="mb-6"><%= flash[:notice] %></p>
    </div>
  </div>

  <div class="row">
    <table>
      <div class="mt-5 p-1 col-md-7">
        <h5>@<%= @user.name %> ( <%= @user.nickname %> ) さんの会員詳細</h5>
      </div>
    </table>
  </div>

  <div class="row">
    <div class="col-md-8">
        <table class="mt-5 col-md-6 text-center border">
            <tr>
              <th class="py-2 border">プロフィール画像</th>
              <td class="border"><%= image_tag @user.get_profile_image(80, 80) %></td>
            </tr>
            <tr>
                <th class="py-2 border">会員ID</th>
                <td class="border"><%= @user.id %></td>
            </tr>
            <tr>
                <th class="p-2 border">アカウント名</th>
                <td class="border">@<%= @user.name %></td>
            </tr>
            <tr>
                <th class="p-2 border">ニックネーム</th>
                <td class="border"><%= @user.nickname %></td>
            </tr>
             <tr>
                <th class="p-2 border">電話番号</th>
                <td class="border"><%= @user.telephone_number %></td>
            </tr>
             <tr>
                <th class="p-2 border">メールアドレス</th>
                <td class="border"><%= @user.email %></td>
            </tr>
            <tr>
                <th class="p-2 border">会員ステータス</th>
                <td class="border"><%= @user.is_active %></td>
            </tr>
            <tr>
                <th class="p-2 border">会員登録日</th>
                <td class="border"><%= @user.created_at.strftime('%Y/%m/%d') %></td>
            </tr>
        </table>

    <div class="mt-3 p-5 col-md-11">
      <tr>
        <%= link_to "編集する", edit_admin_user_path(@user), class: "btn btn-success p-2 mr-4 mb-5" %>
      </tr>
      <tr>
        <%= link_to "<< 会員一覧へ戻る", admin_users_path, class: "btn btn-warning p-2 mr-4 mb-5" %>
      </tr>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7 pt-5">
      <h5 class="pb-5">@<%= @user.name %> ( <%= @user.nickname %> ) さんのレビュー投稿一覧</h5>
      <% @vegetainable_reviews.each do |vegetainable_review| %>
      <table>
        <tr>
          <th nowrap>レビュー投稿日：</th>
          <td><%= vegetainable_review.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>レビューID：</th>
          <td><%= link_to vegetainable_review.id, admin_user_vegetainable_review_path(@user, vegetainable_review) %></td>
        </tr>
        <tr>
          <th>タイトル：</th>
          <td><%= vegetainable_review.title %></td>
        </tr>
        <tr>
          <th nowrap>レビュー内容：</th>
          <td><%= vegetainable_review.caption %></td>
        </tr>
        <tr>
          <th>種類：</th>
          <td><%= vegetainable_review.name %></td>
        </tr>
        <tr>
          <th>産地：</th>
          <td><%= vegetainable_review.area %></td>
        </tr>
        <tr>
          <th>農家：</th>
          <td><%= vegetainable_review.farmer_name %></td>
        </tr>
        <tr>
          <th>販売先：</th>
          <td class="pb-2"><%= vegetainable_review.shop_name %></td>
        </tr>
        <tr>
          <th></th>
          <td><%= link_to 'レビューを削除する', admin_user_vegetainable_review_path(@user.id, vegetainable_review.id), method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-sm btn-danger my-2" %></td>
        </tr>
      </table>
        <tr>
          <th class="p-2">コメント件数：<%= vegetainable_review.comments.count %></th>
          <% vegetainable_review.comments.each do |comment| %>
            <div class="col-sm-5">
              <tr>
                <td><%= image_tag comment.user.get_profile_image(60,60) %> @<%= comment.user.name %>さん</td>
              </tr>
            </div>
            <div class="col-sm-12">
              <tr>
                <td><%= comment.created_at.strftime('%Y/%m/%d') %>：</td>
                <td><%= comment.content %></td>
                <td><%= button_to "削除する", admin_comment_path(comment.id), method: :delete, class: "mt-2 mb-4 btn btn-warning" %></td>
              </tr>
            </div>
          <% end %>
        </tr>
        <hr class="p-2">
      <% end %>
    </div>
  <footer class="pl-5 pt-3 w-50 col-12 pb-5 text-center">
    <%= paginate @vegetainable_review %>
  </footer>
  </div>
</div>