config/routes.rb
Rails.application.routes.draw do
  namespace :user do
    get 'users/index'
    get 'users/show'
    get 'users/edit'
    get 'users/update'
    get 'users/create'
    get 'users/destroy'
  end
get 'users/destroy' => "users#delete"

# 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:passwords], controllers: {
  sessions: "admin/sessions"
}

# ユーザー用
# URL /users/sign_in ...
  devise_for :user, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

  devise_scope :user do
  post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

namespace :admin do
  root to: "homes#top", as: 'top'
   get "homes/about" => "homes#about"
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :vegetainable_reviews, only: [:show, :destroy]
  end
  resources :comments, only: [:destroy]

end

scope module: :user do
  root to: 'homes#top'
  get "homes/about" => "homes#about"
  resources :vegetainable_reviews, only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resource :favorite, only: [:create, :destroy]
  get "search" => "searches#search"
  get 'users/my_page' => "users#mypage", as: 'my_page'
  get '/users/my_page/edit' => "users#edit", as: 'edit_my_page'
  patch '/users/my_page' => "users#update", as: 'update_my_page'
  get '/users/my_page/withdraw_confirmation' => "users#withdraw_confirmation", as: 'withdraw_confirmation_my_page'
  patch '/users/my_page/withdraw' => "users#withdraw", as: 'withdraw_my_page'

  resources :users, only: [:index, :show]

  # get 'vegetainable_review/:id/favorite/new' => "favorites#new", as: 'new_favorite'
  # post 'vegetainable_review/:id/favorite/new' => "favorites#new", as: 'favorite'
  # get '/vegetainable_review/:id/favorite/:id/edit' => "favorite#edit", as: 'edit_favorite'
  # patch '/vegetainable_review/:id/favorite/:id' => "favorite#update", as: 'update_favorite'
  # delete '/vegetainable_review/:id/favorite/:id' => "favorite#destroy", as: 'destroy_favorite'

end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UniqueVegetainable</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/2ff29df84d.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-warning">
    <div class="container">
        <% if admin_signed_in? %>
        <tr>
          <td>
          <%= link_to admin_top_path do %>
            <%= image_tag 'logo.jpg', class: 'hoge' , size: '340x60'%>
          <% end %>
          </td>
        </tr>
        <% elsif user_signed_in? %>
          <%= link_to root_path do %>
            <%= image_tag 'logo.jpg', class: 'hoge' , size: '340x60'%>
          <% end %>
        <% else %>
           <%= image_tag 'logo.jpg', class: 'hoge' , size: '340x60'%>
        <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">

          <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li>
                <%= link_to "ユーザーの一覧", admin_users_path, class: "p-1 m-3 btn btn-success" %>
              </li>
              <li>
                <h6><%= button_to "ログアウト", destroy_admin_session_path, method: :delete, class: "p-1 px-2 m-3 btn btn-secondary" %></h6>
              </li>
            <% elsif user_signed_in? %>
              <li>
                <% if current_user.email != 'guest@vegetainable.com'%>
                <%= link_to 'マイページ', my_page_path, class: "p-1 px-2 m-1 btn btn-success" %>
                <% end %>
              </li>
              <li>
                <%= link_to 'レビューの一覧', vegetainable_reviews_path, class: "p-1 px-2 m-1 btn btn-success text-right " %>
              </li>
              <li>
                  <% if current_user.email != 'guest@vegetainable.com'%>
                  <%= link_to 'レビュー投稿フォーム', new_vegetainable_review_path, class: "p-1 px-2 m-1 btn btn-success text-right " %>
                  <% end %>
              </li>
              <li>
                <%= button_to "ログアウト", destroy_user_session_path, method: :delete, class: "p-1 px-2 m-1 btn btn-secondary text-right " %>
              </li>
            <% else %>
              <li>
                <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "p-1 px-2 m-3 btn btn-success" %>
              </li>
              <li>
                <%= link_to "新規登録", new_user_registration_path, class: "p-1 px-2 m-3 btn btn-success" %>
              </li>
              <li>
                <%= link_to "ログイン", new_user_session_path, class: "p-1 px-2 m-3 btn btn-success" %>
              </li>
            <% end %>
          </ul>
      </div>
    </div>
  </nav>
</header>
<%= yield %>
<div class="mx-0 bg-warning py-1 text-center text-black">
  <h6>@ユニークベジティナブル</h6>
</div>
</html>